'''
    This is a basic Number Guessing code in Python.
    The user is free to write the number of questions he wants to answer.
    If the number generated by the User is higher than that of the computer it simply displays high
    This will help the user to be able to guess the number.
    
'''